remote_theme: artemsheludko/monday
title:  "Maniu"
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "maniu.eu" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: Maniu
tagline: Dev
about-description: # Add Discription
#pic: 79.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: me@maniu.eu # Add your Email address
Phone: #00
website: maniu.eu # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: -- # Add your Github handle
twitter: '@monkey_maniu' # Add your Twitter handle
description: " "

include: [ "/.well-known" ]
