theme: jekyll-theme-dinky
title:  "Maniu"
description: " "
include: [ "/.well-known" ]
show_downloads: false
github:
    is_user_page: false
    is_project_page: false
    repository_url: https://maniu.eu
