theme: jekyll-theme-dinky
title:  "Marek Pistorius"
description: " "
show_downloads: false
github:
    is_user_page: false
    is_project_page: false
    repository_url: https://github.com/marekpistorius
